HR.API/Controllers/FuncionesController.cs
using HR.API.Data;
using HR.API.Data.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HR.API.Controllers
{
    [Authorize(Roles = "Admin")]
    public class FuncionesController:Controller
    {
       
        private readonly DataContext _context;
       
        public FuncionesController(DataContext context)
        {
            _context = context;
        }
        // GET: ReclamoTypes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Funciones.ToListAsync());
        }

        // GET: ReclamoTypes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ReclamoTypes/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Funcion funcion)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Add(funcion);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateException dbUpdateException)
                {

                    if (dbUpdateException.InnerException.Message.Contains("duplicate"))
                    {
                        ModelState.AddModelError(string.Empty, "Ya Existe este Tipo de Funcion");
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, dbUpdateException.InnerException.Message);
                    }
                }
                catch (Exception exception)
                {
                    ModelState.AddModelError(string.Empty, exception.Message);
                }
            }
            return View(funcion);
        }

        // GET: ReclamoTypes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.ReclamoTypes == null)
            {
                return NotFound();
            }

            Funcion? funcion = await _context.Funciones.FindAsync(id);
            if (funcion == null)
            {
                return NotFound();
            }
            return View(funcion);
        }

        // POST: ReclamoTypes/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Funcion funcion)
        {
            if (id != funcion.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(funcion);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateException dbUpdateException)
                {

                    if (dbUpdateException.InnerException.Message.Contains("duplicate"))
                    {
                        ModelState.AddModelError(string.Empty, "Ya Existe este Tipo de Funcion");
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, dbUpdateException.InnerException.Message);
                    }
                }
                catch (Exception exception)
                {
                    ModelState.AddModelError(string.Empty, exception.Message);
                }

            }
            return View(funcion);
        }

        // GET: Funciones/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Funciones == null)
            {
                return NotFound();
            }

            Funcion? funcion = await _context.Funciones
                .FirstOrDefaultAsync(m => m.Id == id);
            if (funcion == null)
            {
                return NotFound();
            }
            _context.Funciones.Remove(funcion);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


    }
}

HR.API/Controllers/ReclamosController.cs
using HR.API.Data;
using HR.API.Data.Entities;
using HR.API.Helpers;
using HR.API.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HR.API.Controllers
{
        [Authorize(Roles = "Admin")]
        public class ReclamosController : Controller
    {
        private bool agregadook = false;
        private readonly DataContext _context;
        private readonly ICombosHelper _combosHelper;
        private readonly IConverterReclamoHelper _converterReclamoHelper;
        private Reclamo reclamo1 = new Reclamo();
        public ReclamosController(DataContext context,ICombosHelper combosHelper,IConverterReclamoHelper converterReclamoHelper)
            {
                _context = context;
                _combosHelper = combosHelper;
                 _converterReclamoHelper = converterReclamoHelper;
        }
            // GET: ReclamoTypes
            public async Task<IActionResult> Index()
            {
                return View(await _context.Reclamos
                    .Include(x=>x.Abonado)
                    .Include(x=>x.ReclamoMateriales)
                    .ThenInclude(c=>c.Material)
                    .Include(x=>x.ReclamoTecnicos)
                    .ThenInclude(v=>v.User)
                    .Include(x=>x.TipoReclamo)
                    .ToListAsync());
            }

            // GET: ReclamoTypes/Create
            public IActionResult Create()
            {
                 ReclamoViewModel model = new ReclamoViewModel
                 {
                     Materiales=_combosHelper.GetComboMateriales(),
                     Tecnicos=_combosHelper.GetComboTecnicos(),
                     TipoReclamos=_combosHelper.GetComboTipodeReclamos(),
                    HLlegada=new DateTime(),
                     HSalida = new DateTime(),
                     Resolucion="_",
                     Observaciones="_",

                 };

                return View(model);
            }

            // POST: ReclamoTypes/Create

            [HttpPost]
            [ValidateAntiForgeryToken]
            public async Task<IActionResult> Create(ReclamoViewModel reclamo)
            {
           
                if (ModelState.IsValid)
                {
                    try
                    {

                        reclamo1 = await _converterReclamoHelper.ToReclamoAsync(reclamo, true);
                        var BuscaAbonado = await _context.Abonados.FirstOrDefaultAsync(x => x.Numero == reclamo.AbonadoId);

                        if (BuscaAbonado != null)
                        {
                          BuscaAbonado.Reclamos.Add(reclamo1);
                        }
                        _context.Add(reclamo1);
                         await _context.SaveChangesAsync();
                        agregadook = true;
                        
                    }
                    catch (DbUpdateException dbUpdateException)
                    {
                    agregadook = false;

                    if (dbUpdateException.InnerException.Message.Contains("duplicate"))
                        {
                            ModelState.AddModelError(string.Empty, "Ya Existe este Reclamo");
                        }
                        else
                        {
                            ModelState.AddModelError(string.Empty, dbUpdateException.InnerException.Message);
                        }
                    }
                    catch (Exception exception)
                    {
                        ModelState.AddModelError(string.Empty, exception.Message);
                    }
                }
            if (agregadook)
            {
                var tecnico=await _context.Users.FirstOrDefaultAsync(x=>x.Id == reclamo.TecnicoId);
                var reclamoBuscar=await _context.Reclamos.FirstOrDefaultAsync(x=>x.Numero == reclamo.Numero);
                //Reclamo reclamo1 = await _converterReclamoHelper.ToReclamoAsync(reclamo, true);
                ReclamoTecnico nuevo = new ReclamoTecnico();
                nuevo.ReclamoId = reclamoBuscar.Id;
                nuevo.User = tecnico;

                _context.Add(nuevo);
                await _context.SaveChangesAsync();
                /*
                var BuscaAbonado = await _context.Abonados.FirstOrDefaultAsync(x => x.Numero == reclamo.AbonadoId);

                if (BuscaAbonado != null)
                {
                    BuscaAbonado.Reclamos.Add(reclamo1);
                }
                else
                {
                    _context.Add(reclamo1.Abonado);
                    await _context.SaveChangesAsync();
                }
 */

                return RedirectToAction(nameof(Index));

            }
            return View(reclamo);
            }

            // GET: ReclamoTypes/Edit/5
            public async Task<IActionResult> Edit(int? id)
            {
                if (id == null || _context.Materiales == null)
                {
                    return NotFound();
                }

                Reclamo? reclamo = await _context.Reclamos.FindAsync(id);
                if (reclamo == null)
                {
                    return NotFound();
                }
                return View(reclamo);
            }

            // POST: ReclamoTypes/Edit/5

            [HttpPost]
            [ValidateAntiForgeryToken]
            public async Task<IActionResult> Edit(int id, Reclamo reclamo)
            {
                if (id != reclamo.Id)
                {
                    return NotFound();
                }

                if (ModelState.IsValid)
                {
                    try
                    {
                        _context.Update(reclamo);
                        await _context.SaveChangesAsync();
                        return RedirectToAction(nameof(Index));
                    }
                    catch (DbUpdateException dbUpdateException)
                    {

                        if (dbUpdateException.InnerException.Message.Contains("duplicate"))
                        {
                            ModelState.AddModelError(string.Empty, "Ya Existe este Reclamo");
                        }
                        else
                        {
                            ModelState.AddModelError(string.Empty, dbUpdateException.InnerException.Message);
                        }
                    }
                    catch (Exception exception)
                    {
                        ModelState.AddModelError(string.Empty, exception.Message);
                    }

                }
                return View(reclamo);
            }

            // GET: Funciones/Delete/5
            public async Task<IActionResult> Delete(int? id)
            {
                if (id == null || _context.Reclamos == null)
                {
                    return NotFound();
                }

                Reclamo? reclamo = await _context.Reclamos
                    .FirstOrDefaultAsync(m => m.Id == id);
                if (reclamo == null)
                {
                    return NotFound();
                }
                _context.Reclamos.Remove(reclamo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }


       
    }
}

HR.API/Controllers/UsersController.cs
using HR.API.Data;
using HR.API.Data.Entities;
using HR.API.Helpers;
using HR.API.Models;
using HR.Common.Enums;
using HR.Common.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HR.API.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        private readonly DataContext _context;
        private readonly IUserHelper _userHelper;
        private readonly ICombosHelper _combosHelper;
        private readonly IConverterHelper _converterHelper;
        private readonly IMailHelper _mailHelper;

        // private readonly IBlodHelper _blobHelper;

        public UsersController(DataContext context, IUserHelper userHelper, ICombosHelper combosHelper,
         IConverterHelper converterHelper,IMailHelper mailHelper)//, IBlodHelper blobHelper)
        {
            _context = context;
            _userHelper = userHelper;
            _combosHelper = combosHelper;
            _converterHelper = converterHelper;
            _mailHelper = mailHelper;
            //  _blobHelper = blobHelper;
        }
        public async Task<IActionResult> Index()
        {
            DateTime dia = new DateTime();
            dia = DateTime.Parse("02/03/04");
            List<Data.Entities.User>? tecnicos = await _context.Users.Where(x => x.UserType == UserType.User)
                      .Include(x => x.ReclamoTecnicos)
                      .ThenInclude(x => x.Reclamo)
                      .Include(x => x.Funcion)
                //.Select(x => new { ReclamoTecnicos = x, Reclamos = x.ReclamoTecnicos.Where(e => e.Reclamo.Fecha == dia) })
                .ToListAsync();
            return View(tecnicos);
        }
        public IActionResult Create()
         {
             UserViewModel model = new UserViewModel
             {
                 Funciones = _combosHelper.GetComboFunciones()
             };
             return View(model);
         }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(UserViewModel model)
        {
            if (!ModelState.IsValid)
            {//TODO:falta colocar la imagen del blob
                Guid imageId = Guid.Empty;
                if(model.ImageFile!=null)
                {
                  //  imageId = await _blobHelper.UploadBlobAsync(model.ImageFile, "users");
                }
                User user = await _converterHelper.ToUserAsync(model, imageId, true);
                user.UserType = UserType.User;
                await _userHelper.AddUserAsync(user, "123456");
                await _userHelper.AddUserToRoleAsync(user, user.UserType.ToString());

                string myToken = await _userHelper.GenerateEmailConfirmationTokenAsync(user);
                string tokenLink = Url.Action("ConfirmEmail", "Account", new
                {
                    userid = user.Id,
                    token = myToken
                }, protocol: HttpContext.Request.Scheme);

                Response response = _mailHelper.SendMail(
                    $"{model.FirstName} {model.LastName}",
                    model.Email,
                    "Hoja De Ruta - Confirmación de Email",
                    $"<h1>Hoja De Ruta  - Confirmación de Email</h1>" +
                        $"Para habilitar el usuario por favor hacer click en el siguiente link:, " +
                        $"<hr/><br/><p><a href = \"{tokenLink}\">Confirmar Email</a></p>");

                    return RedirectToAction(nameof(Index));
            }
            model.Funciones= _combosHelper.GetComboFunciones();
            return View(model);
        }

       
        public async Task<IActionResult> Edit(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            User user = await _userHelper.GetUserAsync(Guid.Parse(id));
            if (user == null)
            {
                return NotFound();
            }
            UserViewModel model = _converterHelper.ToUserViewModel(user);

            return View(model);
        }

        // POST: /Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(UserViewModel model)
        {
           
            if (ModelState.IsValid)
            {
                   Guid imageId=model.ImageId;
                    if(model.ImageFile!=null)
                    {
                        imageId = model.ImageId;// await _blobHelper.UploadBlobAsync(model.ImageFile, "users");
                    }

                    User user = await _converterHelper.ToUserAsync(model, imageId, false);
                    await _userHelper.UpdateUserAsync(user);

                    return RedirectToAction(nameof(Index));
               
            }

            model.Funciones = _combosHelper.GetComboFunciones();
            return View(model);
        }

        public async Task<IActionResult> Delete(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            User user=await _userHelper.GetUserAsync(Guid.Parse(id));
            if (user == null)
            {
                return NotFound();
            }
           
            //TODO falta blob
            
            // await _blobHelper.DeleteBlobAsync(user.ImageId,"users");
            await _userHelper.DeleteUserAsync(user);
            return RedirectToAction(nameof(Index));
        }
    
    
    
    }


}

HR.API/Views/Shared/_DeleteDialog.cshtml
 
<div class ="modal fade" id="deleteDialog" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Borrar Registro</h5>
        </div>
        <div class="modal-body">
            <p>¿Estas Seguro De Borrar El Registro?</p>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-primary" data-bs-dismiss="modal">No</button>
            <button type="button" class="btn btn-danger" id="btnYesDelete">Si</button>
        </div>
       </div>
    </div>
</div>

HR.API/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HR.API</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HR.API.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Hoja de Ruta</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Funciones" asp-action="Index">Tipo de Funciones</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Materiales" asp-action="Index">Tipo de Materiales</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ReclamoTypes" asp-action="Index">Tipo de Reclamos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Tecnicos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Reclamos" asp-action="Index">Reclamos</a>
                            </li>
                        }
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="ChangeUser">@User.Identity.Name</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Cerrar Sesión</a>
                            </li>
                        }
                        else
                        {     
                            <li>
                                <a asp-area="" asp-controller="Account" asp-action="Login">Iniciar Sesión</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Hoja de Ruta - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>